Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Models/Customers_potential.cs
namespace Prj_Dh_Food_Shop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Customers_potential
    {
        public int id { get; set; }

        [Required]
        [StringLength(200)]
        public string name { get; set; }

        [Required]
        [StringLength(15)]
        public string phone_number { get; set; }

        [Required]
        [StringLength(200)]
        public string statuss { get; set; }

        [StringLength(200)]
        public string note { get; set; }

        [Column(TypeName = "date")]
        public DateTime? createAt { get; set; }

        [StringLength(200)]
        public string createBy { get; set; }

        [Column(TypeName = "date")]
        public DateTime? updateAt { get; set; }

        [StringLength(200)]
        public string updateBy { get; set; }
    }
}

Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Controllers/CustomersPotentialController.cs
using Prj_Dh_Food_Shop.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Prj_Dh_Food_Shop.Controllers
{
    public class CustomersPotentialController : BaseController
    {
        private Entity_Dh_Food db = new Entity_Dh_Food();

        public ActionResult Index(Search_CustomersPotential model)
        {
            model.txbName = model.txbName == null ? string.Empty : model.txbName.Trim();
            model.txbPhone = model.txbPhone == null ? string.Empty : model.txbPhone.Trim();

            model.page = model.page == 0 ? 1 : model.page;
            model.pageSize = model.pageSize == 0 ? 5 : model.pageSize;

            var data = from c in db.Customers_potential
                       where (string.IsNullOrEmpty(model.txbName) || c.name.Contains(model.txbName))
                       && (string.IsNullOrEmpty(model.txbPhone) || c.name.Contains(model.txbPhone))
                       && (string.IsNullOrEmpty(model.txbStatus) || c.statuss == model.txbStatus)
                       select new Search_CustomersPotential()
                       {
                           id = c.id,
                           name = c.name,
                           phone_number = c.phone_number,
                           statuss = c.statuss,
                           note = c.note,
                       };

            var rs = data.OrderBy(x => x.statuss).Skip(((model.page - 1) * model.pageSize)).Take(model.pageSize).ToList() ?? new List<Search_CustomersPotential>();
            model.lstData = rs;
            model.totalRecord = data.Count();
            model.totalPage = (int)Math.Ceiling((decimal)model.totalRecord / model.pageSize);
            return View(model);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers_potential cus_pot = db.Customers_potential.Find(id);
            if (cus_pot == null)
            {
                return HttpNotFound();
            }
            return PartialView("PartialEdit", cus_pot);
        }

        [HttpPost]
        public ActionResult Edit(Customers_potential cus_pot)
        {
            var msg = "";
            var status = 0;
            var result = db.Customers_potential.SingleOrDefault(b => b.id == cus_pot.id);

            if (result != null)
            {
                result.statuss = cus_pot.statuss;
                result.note = cus_pot.note;

                db.SaveChanges();
                msg = "Cập nhật thông tin khách hàng thành công!";
                status = 1;
            }
            return Json(new { msg = msg, status = status }, JsonRequestBehavior.AllowGet);
        }



        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers_potential cus_pot = db.Customers_potential.Find(id);
            if (cus_pot == null)
            {
                return HttpNotFound();
            }
            return PartialView("PartialDelete", cus_pot);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var msgDel = "";
            var status = 0;
            Customers_potential cus_pot = db.Customers_potential.Find(id);
            db.Customers_potential.Remove(cus_pot);
            db.SaveChanges();
            msgDel = "Xóa khách hàng thành công!";
            status = 1;

            return Json(new { msg = msgDel, status = status }, JsonRequestBehavior.AllowGet);
        }
    }
}

Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Views/CustomersPotential/Index.cshtml
<link href="/Content/css/n-custom.css" rel="stylesheet">
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="~/Content/css/style.css">

@model Prj_Dh_Food_Shop.Search_CustomersPotential
@{
    var count = 0;
}

<script>
    function delCustomersPotential(id) {
        $.ajax({
            url: '/CustomersPotential/Delete/' + id,
            type: "POST",
            //data: model,
            success: function (rs) {
                if (rs != null && rs != undefined && rs != '') {
                    if (window.confirm(rs.msg)) {
                        if (rs.status == 1)
                            window.location.href = '/CustomersPotential/Index';
                    }
                    else {
                        // They clicked no
                    }

                } else {
                    toastr.error('Có lỗi xảy ra!');
                }
            },
        });
    }

    function editCustomersPotential(id) {
        var model = {
            statuss: $('select[name="statuss"]').val(),
            name: $('input[name="note"]').val(),
        }

        $.ajax({
            url: '/CustomersPotential/Edit/' + id,
            type: "POST",
            data: model,
            success: function (rs) {
                if (rs != null && rs != undefined && rs != '') {
                    if (window.confirm(rs.msg)) {
                        if (rs.status == 1)
                            window.location.href = '/CustomersPotential/Index';
                    }
                    else {
                        // They clicked no
                    }

                } else {
                    toastr.error('Có lỗi xảy ra!');
                }
            },
        });
    }
</script>

<div id="sitemap">
    <ul>
        <li>
            <a>
                <span>Quản lý khách hàng tiềm năng</span>
            </a>
        </li>
    </ul>
</div>
<table style="width: 100%;" class="frmSearch n-tbl-head-1 m-0">
    <tbody>
        <form action="/CustomersPotential/Index" method="post">
            <tr>
                <td style="padding-left: 0; width:110px">
                    <span name="1" style="float: left; font-weight: bold;">Tên khách hàng</span>
                </td>
                <td>
                    <input name="txbName" type="text" maxlength="255" class="trimspace">
                </td>
                <td style="width: 110px">
                    <span name="2" style="float: left; font-weight: bold;">Số điện thoại</span>
                </td>
                <td style="width: 20%;">
                    <input name="txbPhone" type="text" maxlength="255" class="trimspace">
                </td>
                <td style="width:110px">
                    <span name="1" style="float: left; font-weight: bold;">Trạng thái</span>
                </td>
                <td style="padding: 0;width: 15%;">
                    <select class="m_text" name="txbStatus">
                        <option value="">Tất cả</option>
                        <option value="Đã gọi">Đã gọi</option>
                        <option value="Chưa gọi">Chưa gọi</option>
                        <option value="Gọi lại">Gọi lại</option>
                        <option value="Không gọi được">Không gọi được </option>
                    </select>
                </td>
            </tr>
            <tr>
                <td style="padding-top: 13px" ;="" colspan="8">
                    <div style="text-align:center; margin-bottom: 6px">
                        <input type="submit" name="btnSearch" value="Tìm kiếm" class="myButton btnTrimSpace">
                    </div>
                </td>
            </tr>
        </form>
    </tbody>
</table>
<div>
    <div class="table-agile-info">
        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
            <tr style="background-color: #EDEDED">
                <th style="text-align: center">
                    STT
                </th>
                <th>
                    Tên khách hàng
                </th>
                <th style="text-align: center">
                    Số điện thoại
                </th>
                <th style="text-align: center">
                    Trạng thái
                </th>
                <th>
                    Ghi chú
                </th>
                <th style="text-align: center">
                    Sửa
                </th>
                <th style="text-align: center">
                    Xóa
                </th>
            </tr>
            @foreach (var item in Model.lstData)
            {
                count++;
                <tr>
                    <td style="text-align: center">
                        @((Model.page - 1) * Model.pageSize + count)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.phone_number)
                    </td>
                    <td style="text-align: center">
                        @Html.DisplayFor(modelItem => item.statuss)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.note)
                    </td>
                    <td style="text-align: center">
                        <a href="/CustomersPotential/Edit/@item.id" class="btn-load"><i class="fa fa-wrench"></i></a>
                    </td>
                    <td style="text-align: center">
                        <a href="/CustomersPotential/Delete/@item.id" class="btn-load"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </table>

        <!--Paging-->
        <div class="row paging">
            <div class="col-md-3" style="text-align: left; margin-top: 6px; padding: 0px; width: 380px;">
                <label style="color: #007243">Bạn đang xem @((Model.page - 1) * Model.pageSize + 1) đến @((Model.page - 1) * Model.pageSize + count) trong tổng số @Model.totalRecord bản ghi</label>
            </div>
            <div class="col-md-9" style="float: right; padding-right: 0;">
                <ul class="pagination">
                    @{
                        int position;
                        if (Model.page > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "CustomersPotential", new { page = Model.page-1, pageSize = Model.pageSize, txbName = Model.txbName})" tabindex="-1"> << </a>
                            </li>
                        }

                        for (position = 1; position <= Model.totalPage; position++)
                        {

                            if (position == Model.page)
                            {
                                <li class="page-item active"><a class="page-link" href="@Url.Action("Index", "CustomersPotential", new { page = position, pageSize = Model.pageSize, txbName = Model.txbName })">@position</a></li>
                            }

                            else
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("Index", "CustomersPotential", new { page = position, pageSize = Model.pageSize, txbName = Model.txbName })">@position</a></li>
                            }

                        }
                        if (Model.page > 0 && Model.page < Model.totalPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "CustomersPotential", new { page = Model.page+1, pageSize = Model.pageSize, txbName = Model.txbName })" tabindex="-1"> >> </a>
                            </li>
                        }

                        if (Model.totalPage == 0)
                        {
                            <li>
                                <div style="font-weight: bold; color: #007243;" role="status" aria-live="polite">Không có dữ liệu hiển thị</div>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal_dialog" style="width:45%; margin-left:auto; margin-right: auto">
        @*partialView*@
    </div>
</div>

@*<div id="myModalNew" class="modal fade" role="dialog">
        <div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable ui-resizable" tabindex="-1" role="dialog" aria-labelledby="ui-dialog-title-divEditCustomer"
             style="position: absolute; height: 300px; width: 590px; top: 100px; left: 38%;">
            <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                <span class="ui-dialog-title">Thêm loại sản phẩm</span>
            </div>
            <div id="divEditCustomer" style="background-color:#FFF; width: auto; min-height: 0px;" class="ui-dialog-content ui-widget-content" scrolltop="0" scrollleft="0">
                <div id="ctl00_MainContent_udp1_PageUpdateProgress" style="display:none;" role="status" aria-hidden="true">
                </div>
                <form role="form" class="form-horizontal" method="post" action="/Products/Create" onsubmit="return false">
                    @Html.AntiForgeryToken()
                    <table class="n-tbl-head-1" style="margin-bottom: 0">
                        <tbody>
                            <tr style="height: 25px">
                                <td style="width: 150px">
                                    <span id="Name">Tên loại sản phẩm</span> (<span style="color:Red;">*</span>):
                                </td>
                                <td style="width: 300px">
                                    <input type="text" maxlength="255" placeholder="" name="name" class="m_text" required />
                                </td>
                            </tr>
                            <tr style="height: 25px;">
                                <td colspan="2" align="center" style="padding-top: 10px; padding-left: 30%">
                                    <input type="submit" value="Lưu" id="btnSave" class="n-btn-save" onclick="addCategory()">
                                    <input type="submit" value="Quay lại" id="btnBack" data-dismiss="modal" class="n-btn-cancel">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>*@

<script>
    $('.btn-load').on('click', function (e) {
        e.preventDefault();

        var $modal = $('#myModal');
        var $modalDialog = $('.modal_dialog');
        var href = $(this).prop('href');

        // không cho phép tắt modal khi click bên ngoài modal
        var option = { backdrop: 'static' };

        // load modal
        $modalDialog.load(href, function () {
            $modal.modal(option, 'show');
        });
    });
</script>

Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Views/CustomersPotential/PartialDelete.cshtml
@model Prj_Dh_Food_Shop.Customers_potential

<div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable ui-resizable" tabindex="-1" role="dialog" aria-labelledby="ui-dialog-title-divEditCustomer"
     style="position: absolute; height: 108px; width: 29%; top: 10px; left: 38%;">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">  
            <span class="ui-dialog-title">Bạn có chắc chắn muốn xóa khách hàng: @Model.name ?</span>
        </div>
    </div>
    <div class="modal-footer">
        @*<form onsubmit="return false">*@
        <input type="submit" value="Xóa" class="btn btn-danger" onclick="delCustomersPotential(@Model.id)">
        <input type="submit" value="Quay lại" id="btnBack" data-dismiss="modal" class="n-btn-cancel">
        @*</form>*@
    </div>
</div>

Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Views/CustomersPotential/PartialEdit.cshtml
@model Prj_Dh_Food_Shop.Customers_potential

<div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable ui-resizable" tabindex="-1" role="dialog" aria-labelledby="ui-dialog-title-divEditCustomer"
     style="position: absolute; height: 405px; width: auto; top: 100px; left: 38%;">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <span class="ui-dialog-title">Chỉnh sửa thông tin</span>
    </div>
    <div style="background-color:#FFF; width: auto; min-height: 0px;" class="ui-dialog-content ui-widget-content" scrolltop="0" scrollleft="0">
        <div style="display:none;" role="status" aria-hidden="true">
        </div>
            <table class="n-tbl-head-1" style="margin-bottom: 0">
                <tbody>
                    <tr style="height: 25px">
                        <td>
                            <span>Trạng thái</span>(<span style="color:Red;">*</span>):
                        </td>
                        <td style="width: 350px;">
                            <select class="m_text" name="statuss" required>
                                <option value="@Model.statuss" disabled selected>
                                    @if (Model.statuss == "Đã gọi")
                                    {<span>Đã gọi</span>}
                                    else if (Model.statuss == "Chưa gọi")
                                    {<span>Chưa gọi</span>}
                                    else if (Model.statuss == "Gọi lại")
                                    {<span>Gọi lại</span>}
                                    else
                                    {<span>Không gọi được</span>}
                                </option>
                                <option value="Đã gọi">Đã gọi</option>
                                <option value="Chưa gọi">Chưa gọi</option>
                                <option value="Gọi lại">Gọi lại</option>
                                <option value="Không gọi được">Không gọi được </option>
                            </select>
                        </td>
                    </tr>
                    <tr style="height: 25px">
                        <td>
                            <span>Ghi chú</span>(<span style="color:Red;">*</span>):
                        </td>
                        <td>
                            <input type="text" value="@Model.note" maxlength="255" style="height: 90px" placeholder="" name="note" class="m_text" required />
                        </td>
                    </tr>
                    <tr style="height: 25px;">
                        <td colspan="2" align="center" style="padding-top: 10px; padding-left: 30%">
                            <input type="submit" value="Cập nhật" id="btnSave" class="n-btn-save" onclick="editCustomersPotential(@Model.id)">
                            <input type="submit" value="Hủy" id="btnBack" data-dismiss="modal" class="n-btn-cancel">
                        </td>
                    </tr>
                </tbody>
            </table>
    </div>
</div>