Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Models/Feedbacks.cs
namespace Prj_Dh_Food_Shop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Feedbacks
    {
        public int id { get; set; }

        [StringLength(200)]
        public string title { get; set; }

        public string descriptions { get; set; }

        [Column(TypeName = "date")]
        public DateTime? feedback_date { get; set; }

        public int? is_active { get; set; }

        [StringLength(200)]
        public string customer_name { get; set; }

        [StringLength(100)]
        public string addresss { get; set; }

        [StringLength(15)]
        public string phone_number { get; set; }

        [StringLength(100)]
        public string email { get; set; }

        [Column(TypeName = "date")]
        public DateTime? createAt { get; set; }

        [StringLength(200)]
        public string createBy { get; set; }

        [Column(TypeName = "date")]
        public DateTime? updateAt { get; set; }

        [StringLength(200)]
        public string updateBy { get; set; }
    }
}

Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace Prj_Dh_Food_Shop.Controllers
{
    public class FeedbacksController : BaseController
    {
        // GET: Feedbacks
        private Entity_Dh_Food db = new Entity_Dh_Food();
        public ActionResult Index(Search_Feedbacks model)
        {
            model.txbName = model.txbName == null ? string.Empty : model.txbName.Trim();

            model.page = model.page == 0 ? 1 : model.page;
            model.pageSize = model.pageSize == 0 ? 5 : model.pageSize;

            var data = from f in db.Feedbacks
                       where (string.IsNullOrEmpty(model.txbName) || f.customer_name.Contains(model.txbName))
                       && ((model.txb_is_active) == 0 || f.is_active == model.txb_is_active)
                       select new Search_Feedbacks()
                       {
                           id = f.id,
                           customer_name = f.customer_name,
                           phone_number = f.phone_number,
                           addresss = f.addresss,
                           email = f.email,
                           title = f.title,
                           descriptions = f.descriptions,
                           feedback_date = f.feedback_date,
                           is_active = f.is_active
                       };

            var rs = data.OrderBy(x => x.is_active).Skip(((model.page - 1) * model.pageSize)).Take(model.pageSize).ToList() ?? new List<Search_Feedbacks>();

            ViewBag.customer = new FeedbacksController().getCustomers();

            model.lstData = rs;
            model.totalRecord = data.Count();
            model.totalPage = (int)Math.Ceiling((decimal)model.totalRecord / model.pageSize);
            return View(model);
        }

        public List<Customers> getCustomers()
        {
            var model = db.Customers.ToList();
            return model;
        }

        [HttpPost]
        public ActionResult Edit(int? id)
        {
            var msg = "";
            var status = 0;
            var result = db.Feedbacks.SingleOrDefault(b => b.id == id);

            if (result != null)
            {
                SendEmail(result.id);
                result.is_active = 2;
                db.SaveChanges();
                msg = "Gửi phản hồi thành công!";
                status = 1;
            }
            return Json(new { msg = msg, status = status }, JsonRequestBehavior.AllowGet);
        }

        public void SendEmail(int id)
        {
            string from = ConfigurationManager.AppSettings["FromAddress"].ToString();
            string pass = ConfigurationManager.AppSettings["PasswordFromAddress"].ToString();
            string host = ConfigurationManager.AppSettings["HostMail"].ToString();
            string name = ConfigurationManager.AppSettings["NameDisplayEmail"].ToString();
            string to = (from s in db.Feedbacks
                         where s.id == id
                         select s.email).FirstOrDefault();


            string strSubject = $"Lời cảm ơn từ Dh Foods!";
            string strMsg = "<b>XIN CHÀO ANH/CHỊ !!!</b><br />" +
                            " Thay mặt cho công ty Dh_foods. Em xin cảm ơn anh/chị đã góp ý, phản hồi về sản phẩm và chất lượng sản phẩm của bên em. Em xin ghi nhận ý kiến của anh/chị và cố gắng hoàn thiện sản phẩm. <br /><br />" +
                            "<b> CHÚC ANH/CHỊ MỘT NGÀY VUI VẺ!!!</b> ";

            MailAddress fromAddress = new MailAddress(from, name);
            MailAddress toAddress = new MailAddress(to, from);

            SmtpClient smtp = new SmtpClient
            {
                Host = host,
                Port = 587,
                EnableSsl = true,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, pass),
                DeliveryMethod = SmtpDeliveryMethod.Network,
            };

            using (MailMessage mailMessage = new MailMessage(fromAddress, toAddress)
            {
                Subject = strSubject,
                Body = strMsg,
                IsBodyHtml = true,
            })
            {
                try
                {
                    mailMessage.AlternateViews.Add(GetEmbeddedImage(strMsg));
                    smtp.Send(mailMessage);
                }
                catch (Exception ex)
                {
                    View(ex.Message);
                }
            }
        }

        public AlternateView GetEmbeddedImage(string email)
        {
            var baseDirectory = System.AppDomain.CurrentDomain.BaseDirectory;
            string path = Path.Combine(baseDirectory, "assets", "img", "dhfood_logo.png");
            LinkedResource res = new LinkedResource(path);
            res.ContentId = Guid.NewGuid().ToString();
            string img = @"<img src='cid:" + res.ContentId + @"'/>";
            email = String.Format(email, img);
            AlternateView alternateView = AlternateView.CreateAlternateViewFromString(email, null, MediaTypeNames.Text.Html);
            alternateView.LinkedResources.Add(res);
            return alternateView;
        }
    }
}

Prj_Dh_Food_Shop/Prj_Dh_Food_Shop/Views/Feedbacks/Index.cshtml
<link href="/Content/css/n-custom.css" rel="stylesheet">
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="~/Content/css/style.css">


@model Prj_Dh_Food_Shop.Search_Feedbacks
@{

    var count = 0;
}

<script>
    function editOrder(id) {

        $.ajax({
            url: '/Feedbacks/Edit/' + id,
            type: "POST",
            success: function (rs) {
                if (rs != null && rs != undefined && rs != '') {
                    if (window.confirm(rs.msg)) {
                        if (rs.status == 1)
                            window.location.href = '/Feedbacks/Index';
                    }
                    else {
                        // They clicked no
                    }

                } else {
                    toastr.error('Có lỗi xảy ra!');
                }
            },
        });
    }
</script>

<div id="sitemap">
    <ul>
        <li>
            <a>
                <span>Quản lý phản hồi khách hàng</span>
            </a>
        </li>
    </ul>
</div>
<table style="width: 100%;" class="frmSearch n-tbl-head-1 m-0">
    <tbody>
        <form action="/Feedbacks/Index" method="post">
            <tr>
                <td style="padding-left: 0; width:110px">
                    <span name="1" style="float: left; font-weight: bold">Tên khách hàng</span>
                </td>
                <td>
                    <input name="txbName" type="text" maxlength="255" class="trimspace">
                </td>
                <td style="width:120px">
                    <span name="2" style="float: left; margin-left: 10px; font-weight: bold">Trang thái</span>
                </td>
                <td style="padding: 0;width: 15%;">
                    <select class="m_text" name="txb_is_active">
                        <option value="0">Tất cả</option>
                        <option value="1">Chưa phản hồi</option>
                        <option value="2">Đã phản hồi</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td style="padding-top: 13px" ;="" colspan="8">
                    <div style="text-align:center; margin-bottom: 6px">
                        <input type="submit" name="btnSearch" value="Tìm kiếm" class="myButton btnTrimSpace">
                    </div>
                </td>
            </tr>
        </form>
    </tbody>
</table>
<div>
    <div class="table-agile-info">
        <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
            <tr style="background-color: #EDEDED">
                <th style="text-align: center">
                    STT
                </th>
                <th style="width: 150px">
                    Tên khách hàng
                </th>
                <th>
                    Số điện thoại
                </th>
                <th>
                    Email
                </th>
                <th>
                    Tiêu đề
                </th>
                <th>
                    Chi tiết
                </th>
                <th>
                    Ngày phản hồi
                </th>
                <th style="text-align: center">
                    Trạng thái
                </th>
                <th style="text-align: center">
                    Phản hồi
                </th>
            </tr>

            @foreach (var item in Model.lstData)
            {
                count++;
            <tr>
                <td style="text-align: center">
                    @((Model.page - 1) * Model.pageSize + count)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.customer_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phone_number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descriptions)
                </td>
                <td>
                    @item.feedback_date.Value.ToString("dd/MM/yyyy")
                </td>
                <td style="text-align: center">
                    @if (item.is_active == 2)
                    {<span>Đã phản hồi</span>}
                    else
                    {<span>Chưa phản hồi</span>}
                </td>
                <td style="text-align: center">
                    @if (item.is_active == 1)
                    {<a class="btn-load"><i class="far fa-envelope fa-2x" onclick="editOrder(@item.id)"></i></a>}
                    else
                    {<a href="" class="btn-load"><i class="far fa-envelope-open fa-2x"></i></a>}

                </td>
            </tr>
            }
        </table>

        <!--Paging-->
        <div class="row paging">
            <div class="col-md-3" style="text-align: left; margin-top: 6px; padding: 0px; width: 380px;">
                <label style="color: #007243">Bạn đang xem @((Model.page - 1) * Model.pageSize + 1) đến @((Model.page - 1) * Model.pageSize + count) trong tổng số @Model.totalRecord bản ghi</label>
            </div>
            <div class="col-md-9" style="float: right; padding-right: 0;">
                <ul class="pagination">
                    @{
                        int position;
                        if (Model.page > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Feedbacks", new { page = Model.page-1, pageSize = Model.pageSize, txbName = Model.txbName, txb_is_active = Model.txb_is_active })" tabindex="-1"> << </a>
                            </li>
                        }

                        for (position = 1; position <= Model.totalPage; position++)
                        {

                            if (position == Model.page)
                            {
                                <li class="page-item active"><a class="page-link" href="@Url.Action("Index", "Feedbacks", new { page = position, pageSize = Model.pageSize,  txbName = Model.txbName, txb_is_active = Model.txb_is_active })">@position</a></li>
                            }

                            else
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("Index", "Feedbacks", new { page = position, pageSize = Model.pageSize, txbName = Model.txbName, txb_is_active = Model.txb_is_active  })">@position</a></li>
                            }

                        }
                        if (Model.page > 0 && Model.page < Model.totalPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Feedbacks", new { page = Model.page+1, pageSize = Model.pageSize,  txbName = Model.txbName, txb_is_active = Model.txb_is_active })" tabindex="-1"> >> </a>
                            </li>
                        }

                        if (Model.totalPage == 0)
                        {
                            <li>
                                <div style="font-weight: bold; color: #007243;" role="status" aria-live="polite">Không có dữ liệu hiển thị</div>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal_dialog" style="width:45%; margin-left:auto; margin-right: auto">
        @*partialView*@
    </div>
</div>